"""Regenerates every image in content/core/art. Run from the repository root:

    python3 -m tools.art.generate
"""
import json
import pathlib

from . import objects, portraits, soldiers, terrain

ROOT = pathlib.Path("content/core/art")
LICENSE = "Generated by tools/art (No Man's Forest). Licensed CC BY-SA 4.0.\n"


def main():
    for sub in ("soldiers", "portraits", "objects", "terrain"):
        (ROOT / sub).mkdir(parents=True, exist_ok=True)
    for faction in soldiers.FACTIONS:
        soldiers.sheet(faction).save(ROOT / "soldiers" / f"{faction}.png", optimize=True)
        portraits.strip(faction).save(ROOT / "portraits" / f"{faction}.png", optimize=True)
    (ROOT / "soldiers" / "sheet.json").write_text(json.dumps(soldiers.sheet_meta(), indent=2) + "\n")
    catalog = {}
    for name, (size, count, _) in objects.OBJECTS.items():
        objects.strip(name).save(ROOT / "objects" / f"{name}.png", optimize=True)
        catalog[name] = {"size": size, "count": count}
    (ROOT / "objects" / "objects.json").write_text(json.dumps({"objects": catalog}, indent=2) + "\n")
    for i, (name, make) in enumerate(terrain.TEXTURES.items()):
        make(10 + i).save(ROOT / "terrain" / f"{name}.png", optimize=True)
    (ROOT / "LICENSE.txt").write_text(LICENSE)
    print(f"wrote art to {ROOT}")


if __name__ == "__main__":
    main()
